#! /bin/sh

#АВТОЗАПУСК
sxhkd &
$HOME/.config/polybar/launch.sh &
picom --experimental-backend &
nitrogen --restore &
#alacritty &
#telegram-desktop &
#yandex-browser-stable &
dunst &
sycthing &
while ! python /home/Ame/.scripts/noisy/noisy/noisy.py --config /home/Ame/.scripts/noisy/noisy/config.json; do sleep 4; done &
setxkbmap -layout us,ru -option grp:alt_shift_toggle &


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         1
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bsoc config focused_border_color "#f9f8fe"

bspc config border_width	 2
bspc config window_gap		 12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color "#fd2e59"

#ПРАВИЛА ДЛЯ ПОЯВЛЕНИЯ ОКОН
bspc rule -a Alacritty desktop='^4'
bspc rule -a TelegramDesktop desktop='^5'
bspc rule -a Yandex-browser desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


